=begin
#RDA Collections API

#The RDA Collections API Recommendation is a unified model and interface specification for CRUD operations on data collections, with particular observance of persistent identification and typing aspects. The recommendation allows building collections within diverse domains and then sharing or expanding them across disciplines.

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module CollectionsClient
  # Capabilities define the set of actions that are supported by a collection.
  class CollectionCapabilities
    # Identifies whether the collection items are kept in a consistent, meaningful order. The exact nature of the ordering is not specified, but see also appendsToEnd property.
    attr_accessor :is_ordered

    # For an ordered collection, indicates that new items are appended to the end rather than insertable at a specified, possibly invalid, index points. Only valid if isOrdered is true.
    attr_accessor :appends_to_end

    # Indicates whether the collection supports assigning roles to its member items. Available roles are determined by the Collection Model type.
    attr_accessor :supports_roles

    # Indicates whether collection membership mutable (i.e. whether members can be added and removed)
    attr_accessor :membership_is_mutable

    # Indicates whether collection properties are mutable (i.e. can the metadata of this collection be changed)
    attr_accessor :properties_are_mutable

    # If specified, indicates that the collection is made up of homogenous items of the specified type. Type should be specified using the PID of a registered Data Type or a controlled vocabulary.
    attr_accessor :restricted_to_type

    # The maximum length of the Collection. -1 means length is not restricted.
    attr_accessor :max_length


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'is_ordered' => :'isOrdered',
        :'appends_to_end' => :'appendsToEnd',
        :'supports_roles' => :'supportsRoles',
        :'membership_is_mutable' => :'membershipIsMutable',
        :'properties_are_mutable' => :'propertiesAreMutable',
        :'restricted_to_type' => :'restrictedToType',
        :'max_length' => :'maxLength'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'is_ordered' => :'BOOLEAN',
        :'appends_to_end' => :'BOOLEAN',
        :'supports_roles' => :'BOOLEAN',
        :'membership_is_mutable' => :'BOOLEAN',
        :'properties_are_mutable' => :'BOOLEAN',
        :'restricted_to_type' => :'String',
        :'max_length' => :'Integer'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'isOrdered')
        self.is_ordered = attributes[:'isOrdered']
      else
        self.is_ordered = false
      end

      if attributes.has_key?(:'appendsToEnd')
        self.appends_to_end = attributes[:'appendsToEnd']
      else
        self.appends_to_end = true
      end

      if attributes.has_key?(:'supportsRoles')
        self.supports_roles = attributes[:'supportsRoles']
      else
        self.supports_roles = false
      end

      if attributes.has_key?(:'membershipIsMutable')
        self.membership_is_mutable = attributes[:'membershipIsMutable']
      else
        self.membership_is_mutable = true
      end

      if attributes.has_key?(:'propertiesAreMutable')
        self.properties_are_mutable = attributes[:'propertiesAreMutable']
      else
        self.properties_are_mutable = true
      end

      if attributes.has_key?(:'restrictedToType')
        self.restricted_to_type = attributes[:'restrictedToType']
      end

      if attributes.has_key?(:'maxLength')
        self.max_length = attributes[:'maxLength']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @is_ordered.nil?
      return false if @appends_to_end.nil?
      return false if @supports_roles.nil?
      return false if @membership_is_mutable.nil?
      return false if @properties_are_mutable.nil?
      return false if @restricted_to_type.nil?
      return false if @max_length.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          is_ordered == o.is_ordered &&
          appends_to_end == o.appends_to_end &&
          supports_roles == o.supports_roles &&
          membership_is_mutable == o.membership_is_mutable &&
          properties_are_mutable == o.properties_are_mutable &&
          restricted_to_type == o.restricted_to_type &&
          max_length == o.max_length
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [is_ordered, appends_to_end, supports_roles, membership_is_mutable, properties_are_mutable, restricted_to_type, max_length].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CollectionsClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
