=begin
#RDA Collections API

#API Strawman for RDA Research Data Collections WG

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module CollectionsClient
  # Describes the properties of the response to the Service /features request.
  class ServiceFeatures
    # Indicates whether this services provides collection PIDs for new collections. If this is false, requests for new Collections must supply the PID for the collection. If this is true, the Service will use its default PID provider (as advertised via the collectionPidProviderType feature) to create new PIDs to assign to new Collections.
    attr_accessor :provides_collection_pids

    # Identifies the PID provider service used by the Collection Service to create new PIDs for new Collection. Required if providesCollectionPids is true, otherwise this property is optional and has no meaning. Recommended to use a Controlled Vocabulary or registered Data Types
    attr_accessor :collection_pid_provider_type

    # Indicates whether or not the service enforces access controls on requests. Implementation details access are left up to the implementor. This flag simply states whether or not the Service enforces access.
    attr_accessor :enforces_access

    # Indicates whether or not the service offers pagination (via cursors) of response data.
    attr_accessor :supports_pagination

    # Indicates whether or not actions such as update, delete occur synchronously or may be queued for later action.
    attr_accessor :asynchronous_actions

    # Indicates whether or not the service allows rule-based generation of new collections.
    attr_accessor :rule_based_generation

    # The maximum depth to which collection members can be expanded. A value of 0 means that expansion is not supppoted. A value of -1 means that the collections can be expanded to infinite depth.
    attr_accessor :max_expansion_depth

    # Indicates whether the service offers support for versioning of Collections. Implementation details are left up to the implementor.
    attr_accessor :provides_versioning

    # List of collection-level set operations that are supported by this service.
    attr_accessor :supported_collection_operations

    # List of collection model types supported by this service.  Recommended to use a Controlled Vocabulary or registered Data Types
    attr_accessor :supported_model_types


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'provides_collection_pids' => :'providesCollectionPids',
        :'collection_pid_provider_type' => :'collectionPidProviderType',
        :'enforces_access' => :'enforcesAccess',
        :'supports_pagination' => :'supportsPagination',
        :'asynchronous_actions' => :'asynchronousActions',
        :'rule_based_generation' => :'ruleBasedGeneration',
        :'max_expansion_depth' => :'maxExpansionDepth',
        :'provides_versioning' => :'providesVersioning',
        :'supported_collection_operations' => :'supportedCollectionOperations',
        :'supported_model_types' => :'supportedModelTypes'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'provides_collection_pids' => :'BOOLEAN',
        :'collection_pid_provider_type' => :'String',
        :'enforces_access' => :'BOOLEAN',
        :'supports_pagination' => :'BOOLEAN',
        :'asynchronous_actions' => :'BOOLEAN',
        :'rule_based_generation' => :'BOOLEAN',
        :'max_expansion_depth' => :'Integer',
        :'provides_versioning' => :'BOOLEAN',
        :'supported_collection_operations' => :'Array<null>',
        :'supported_model_types' => :'Array<null>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'providesCollectionPids')
        self.provides_collection_pids = attributes[:'providesCollectionPids']
      else
        self.provides_collection_pids = false
      end

      if attributes.has_key?(:'collectionPidProviderType')
        self.collection_pid_provider_type = attributes[:'collectionPidProviderType']
      end

      if attributes.has_key?(:'enforcesAccess')
        self.enforces_access = attributes[:'enforcesAccess']
      else
        self.enforces_access = false
      end

      if attributes.has_key?(:'supportsPagination')
        self.supports_pagination = attributes[:'supportsPagination']
      else
        self.supports_pagination = false
      end

      if attributes.has_key?(:'asynchronousActions')
        self.asynchronous_actions = attributes[:'asynchronousActions']
      else
        self.asynchronous_actions = false
      end

      if attributes.has_key?(:'ruleBasedGeneration')
        self.rule_based_generation = attributes[:'ruleBasedGeneration']
      end

      if attributes.has_key?(:'maxExpansionDepth')
        self.max_expansion_depth = attributes[:'maxExpansionDepth']
      end

      if attributes.has_key?(:'providesVersioning')
        self.provides_versioning = attributes[:'providesVersioning']
      else
        self.provides_versioning = false
      end

      if attributes.has_key?(:'supportedCollectionOperations')
        if (value = attributes[:'supportedCollectionOperations']).is_a?(Array)
          self.supported_collection_operations = value
        end
      end

      if attributes.has_key?(:'supportedModelTypes')
        if (value = attributes[:'supportedModelTypes']).is_a?(Array)
          self.supported_model_types = value
        end
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @provides_collection_pids.nil?
      return false if @enforces_access.nil?
      return false if @supports_pagination.nil?
      return false if @asynchronous_actions.nil?
      return false if @rule_based_generation.nil?
      return false if @max_expansion_depth.nil?
      return false if @provides_versioning.nil?
      return false if @supported_collection_operations.nil?
      return false if @supported_model_types.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          provides_collection_pids == o.provides_collection_pids &&
          collection_pid_provider_type == o.collection_pid_provider_type &&
          enforces_access == o.enforces_access &&
          supports_pagination == o.supports_pagination &&
          asynchronous_actions == o.asynchronous_actions &&
          rule_based_generation == o.rule_based_generation &&
          max_expansion_depth == o.max_expansion_depth &&
          provides_versioning == o.provides_versioning &&
          supported_collection_operations == o.supported_collection_operations &&
          supported_model_types == o.supported_model_types
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [provides_collection_pids, collection_pid_provider_type, enforces_access, supports_pagination, asynchronous_actions, rule_based_generation, max_expansion_depth, provides_versioning, supported_collection_operations, supported_model_types].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = CollectionsClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
