=begin
#RDA Collections API

#API Strawman for RDA Research Data Collections WG

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for CollectionsClient::CollectionsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CollectionsApi' do
  before do
    # run before each test
    @instance = CollectionsClient::CollectionsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollectionsApi' do
    it 'should create an instact of CollectionsApi' do
      expect(@instance).to be_instance_of(CollectionsClient::CollectionsApi)
    end
  end

  # unit tests for collections_get
  # Get a list of all collections
  # This request returns a list of the collections provided by this service.  This may be a complete list, or if the service features include support for pagination, the cursors in the response may be used to iterate backwards and forwards through pages of partial results. Query parameters may be used to supply filtering criteria for the response. When combining filters of different types, the boolean AND will be used. When combining multiple instances of filters of the same type, the boolean OR will be used.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :f_model_type Filter response by the modelType property of the collection.
  # @option opts [String] :f_member_type Filter response by the data type of contained collection member. A collection will meet this requirement if any of its members are of the requested type.
  # @option opts [String] :f_ownership Filter response by the ownership property of the collection
  # @return [CollectionResultSet]
  describe 'collections_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_capabilities_get
  # Get the capabilities of this collection
  # This request returns the capabilities metadata for the collection identified by the supplied id. The collection capabilities describe the actions and operations that are available for this collection.
  # @param id Identifier for the collection
  # @param [Hash] opts the optional parameters
  # @return [CollectionCapabilities]
  describe 'collections_id_capabilities_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_delete
  # Delete a collection
  # This request deletes the collection idenified by the provided id from the collection store. The response may differ depending upon whether or not the service features include support for synchronous actions.
  # @param id identifier for the collection
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'collections_id_delete test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_get
  # Get the properties of a specific collection.
  # This request returns the Collection Object Properties for the collection identified by the provided id.
  # @param id Identifier for the collection
  # @param [Hash] opts the optional parameters
  # @return [CollectionObject]
  describe 'collections_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_ops_find_match_post
  # Find member objects in a collection which match the supplied member object
  # This request accepts as input the complete or partial properties of a member object and returns a ResultSet containing any objects which were deemed to &#39;match&#39; the supplied properties among the members of the identified collection. If the service features include support for pagination, a cursor may be supplied to iterate backwards and forwards through paged results from prior executions of this query.
  # @param id identifier for the collection
  # @param member_properties the member item properties to use when matching
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor If the service supports pagination and a cursor was returned in a prior  response to this query, this can be used to requeste a particular page of the  results.
  # @return [MemberResultSet]
  describe 'collections_id_ops_find_match_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_ops_flatten_get
  # Flattens the collection
  # This request returns a resultset which is a flattened representation of a collection of collections into a single collection.
  # @param id Identifier for the collection to be flattened
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor If the service supports pagination and a cursor was returned in a prior response to this query, this can be used to requeste a particular page of the results.
  # @return [MemberResultSet]
  describe 'collections_id_ops_flatten_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_ops_intersection_other_id_get
  # Retrieve the members at the intersection of two collections
  # This request returns a resultset containing the members at the intersection of two collections. If the service features include support for pagination, a cursor may be supplied to iterate backwards and forwards through paged results from prior executions of this query. The response may be an empty set.
  # @param id Identifier for the first collection in the operation
  # @param other_id Identifier for the second collection in the operation
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor If the service supports pagination and a cursor was returned in a prior response to this query, this can be used to requeste a particular page of the results.
  # @return [MemberResultSet]
  describe 'collections_id_ops_intersection_other_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_ops_union_other_id_get
  # Retrieve the union of two collections
  # This request returns a resultset containing the members at the union of two collections. If the service features include support for pagination, a cursor may be supplied to iterate backwards and forwards through paged results from prior executions of this query. The response may be an empty set.
  # @param id Identifier for the first collection in the operation
  # @param other_id Identifier for the second collection in the operation
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor If the service supports pagination and a cursor was returned in a prior response to this query, this can be used to requeste a particular page of the results.
  # @return [MemberResultSet]
  describe 'collections_id_ops_union_other_id_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_id_put
  # Update the properties of a Collection Object
  # This request updates the properties of the collection identified by the provided id. The updated collection properties must be supplied in the body of the request. The response may differ depending upon whether or not the  service features include support for syncrhonous actions.
  # @param id Persistent identifier for the collection
  # @param content The properties of the colleciton to be updated.
  # @param [Hash] opts the optional parameters
  # @return [CollectionObject]
  describe 'collections_id_put test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for collections_post
  # Create a new collection.
  # This request adds a new collection to the collection store.  The Collection Object properties must be supplied in the  body of the request. 
  # @param content The properties of the collection.
  # @param [Hash] opts the optional parameters
  # @return [CollectionObject]
  describe 'collections_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
