=begin
#RDA Collections API

#API Strawman for RDA Research Data Collections WG

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for CollectionsClient::ServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ServiceApi' do
  before do
    # run before each test
    @instance = CollectionsClient::ServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ServiceApi' do
    it 'should create an instact of ServiceApi' do
      expect(@instance).to be_instance_of(CollectionsClient::ServiceApi)
    end
  end

  # unit tests for features_get
  # Gets the service-level features.
  # This request returns the service-level features. Examples of service-level features might include whether or not the service supports assignment of PIDs for collection members, whether it supports pagination and cursors, whether it enforces  access controls, etc.
  # @param [Hash] opts the optional parameters
  # @return [ServiceFeatures]
  describe 'features_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
